<?php
/**
 * Decides whether an automatic email (the Telegram invitation, osTicket's
 * new-ticket auto-response) may be sent to the sender of a new ticket.
 *
 * Every automatic email that lands on a robot is a liability: auto-responders
 * answer it (Amazon, help desks) and the answer becomes a new ticket, bounces
 * loop back into the support inbox, and mailing spam senders is backscatter —
 * the fastest way to get the sending IP blocklisted.
 *
 * Pure PHP with no osTicket or DB dependencies so it can be unit tested and
 * replayed against historical headers. The DB-backed throttles (per-address
 * cooldown, hourly cap) live in TgUserLinkStore.
 *
 * @license GPL-2.0-or-later
 */
class TgInviteGuard {

    /** Our own invitation subject contains this; replies to it must never trigger another one. */
    const INVITE_SUBJECT_MARKER = 'Vincula tu Telegram';

    /** Mailboxes that are never read, even with a suffix: noreply-mx@, bounces+123@, mailer-daemon.x@ */
    const SYSTEM_LOCAL_PART = '/^(mailer-daemon|postmaster|bounces?|no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|no[-_.]?respon(der|da)|no[-_.]?contestar)([+._-].*)?$/';

    /** Role mailboxes run by software. Exact match (optionally +tag) so news.carlos@ or system.juan@ stay human. */
    const ROLE_LOCAL_PART = '/^(automated|system|abuse|root|daemon|nobody|mailnull|wordpress|www-data|apache|nginx|cron|notifications?|notify|notificacion(es)?[a-z]*|alerts?|alertas?|alerta[a-z]{2,4}|avisos?|news|newsletters?|store-news|marketing|mailer|auto-?reply|autoresponder|auto-?confirm|returns?|pickup-point|shipment-tracking|order-update|updates?|surveys?|encuestas?)(\+.*)?$/';

    /** "no-reply" anywhere as a separated token: billing-noreply@, cuenta.no_responder@ */
    const NOREPLY_TOKEN = '/(^|[+._-])(no[-_.]?reply|do[-_.]?not[-_.]?reply|donotreply|no[-_.]?responder|noresponder|no[-_.]?contestar)([+._-]|$)/';

    /** First label of a sending subdomain used by bulk/transactional senders (e.g. updates.paypal.com). */
    const AUTOMATED_SUBDOMAIN = '/^(bounces?|updates?|notifications?|notificacion(es)?|news|newsletters?|marketing|mailer|mkt|em|e|alerts?|alertas|avisos|txn|reply\d*|campaigns?|promo|mailings?|no-?reply|no-?responder)$/';

    /** Subject prefixes of out-of-office / auto-reply messages in the languages we see. */
    const AUTO_REPLY_SUBJECT = '/^\s*(automatic reply|auto[- ]?(reply|response)|respuesta autom[aá]tica|resposta autom[aá]tica|r[ée]ponse automatique|automatische antwort|out of (the )?office|fuera de (la )?oficina)\s*:/iu';

    /** Zero-width and invisible characters used to dodge filters ("A​mazon"). */
    const INVISIBLE_CHARS = '/[\x{00AD}\x{034F}\x{200B}-\x{200F}\x{2060}-\x{2064}\x{FEFF}]/u';

    /**
     * Notification-only brand domains (and all their subdomains). Nobody
     * opens a support ticket from these; anything they send is automated.
     */
    const BRAND_DOMAINS = array(
        'amazon.com', 'amazon.com.mx', 'amazon.ca', 'amazon.es', 'amazon.co.uk', 'amazon.de', 'amazon.com.br',
        'amazonses.com',
        'paypal.com', 'paypal.com.mx', 'paypal-customerfeedback.com',
        'mercadolibre.com', 'mercadolibre.com.mx', 'mercadopago.com', 'mercadopago.com.mx', 'mercadocredito.com.mx',
        'facebookmail.com', 'instagram.com', 'whatsapp.com', 'tiktok.com', 'linkedin.com',
        'youtube.com', 'twitter.com', 'x.com', 'discord.com',
        'google.com', 'apple.com', 'microsoft.com', 'stripe.com', 'shopifyemail.com',
    );

    /**
     * Header → matcher. '*' means presence alone is enough; an array lists
     * uppercase substrings, any of which must appear in the value.
     */
    const AUTOMATION_HEADERS = array(
        // RFC 3834 / legacy auto-responder markers
        'precedence'                => array('BULK', 'LIST', 'JUNK', 'AUTO_REPLY'),
        'x-precedence'              => array('BULK', 'LIST', 'JUNK', 'AUTO_REPLY'),
        'x-autoreply'               => '*',
        'x-autorespond'             => '*',
        'x-autoresponse'            => '*',
        'x-autoreply-from'          => '*',
        'x-mail-autoreply'          => '*',
        'x-autogenerated'           => '*',
        'x-auto-response-suppress'  => array('ALL', 'OOF', 'AUTOREPLY'),
        'x-amazon-auto-reply'       => '*',
        'x-ms-exchange-inbox-rules-loop' => '*',
        'x-ms-exchange-generated-message-source' => array('MAILBOX RULES AGENT'),
        // Mailing lists and bulk senders
        'list-unsubscribe'          => '*',
        'list-id'                   => '*',
        'list-post'                 => '*',
        'x-report-abuse'            => '*',
        'x-csa-complaints'          => '*',
        'feedback-id'               => '*',
        // Transactional email services
        'x-ses-outgoing'            => '*',
        'x-amazon-mail-relay-type'  => '*',
        'bounces-to'                => '*',
        'x-mailgun-sid'             => '*',
        'x-sg-eid'                  => '*',
        'x-sg-id'                   => '*',
        'x-mandrill-user'           => '*',
        'x-mc-user'                 => '*',
        'x-pm-message-id'           => '*',
        'x-sfmc-stack'              => '*',
        'x-mailjet-campaign'        => '*',
        'x-sib-id'                  => '*',
        'x-mailin-eid'              => '*',
        'x-campaign'                => '*',
        'x-campaignid'              => '*',
        // Delivery status notifications
        'x-failed-recipients'       => '*',
    );

    /**
     * Headers that personal mailbox providers add to ordinary person-to-person
     * mail (Amazon WorkMail sends through SES, ProtonMail and Telmex set
     * Feedback-ID). For those senders they are not a sign of automation.
     */
    const PERSONAL_PROVIDER_EXEMPT = array('feedback-id', 'x-ses-outgoing');

    /**
     * Returns a short machine-readable reason when the automatic email must
     * NOT be sent, or null when the recipient looks like a human.
     *
     * @param string            $email    recipient (the ticket owner's address)
     * @param string|array|null $headers  raw headers of the email that opened the ticket,
     *                                    or a parsed array; null/'' for web/API tickets
     * @param array             $context  optional:
     *   'subject'       => ticket subject
     *   'name'          => sender display name
     *   'own_domains'   => string[] domains of the helpdesk's own mailboxes
     *   'skip_list'     => string[] admin-configured domains and full addresses to never mail
     *   'invite_sender' => address the invitation is sent from (replies to it are loops)
     * @return string|null
     */
    public static function skipReason($email, $headers = null, array $context = array()) {
        $email = strtolower(trim((string) $email));
        $at = strrpos($email, '@');
        if ($at === false || $at === 0) {
            return 'invalid-email';
        }
        $local  = substr($email, 0, $at);
        $domain = substr($email, $at + 1);
        if (preg_match('/\s/', $local)
                || !preg_match('/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/', $domain)) {
            return 'invalid-email';
        }

        $subject = isset($context['subject']) ? preg_replace('/\s+/u', ' ', (string) $context['subject']) : '';
        $name    = isset($context['name']) ? (string) $context['name'] : '';

        if ($subject !== '' && stripos($subject, self::INVITE_SUBJECT_MARKER) !== false) {
            return 'reply-to-invite';
        }
        if ($subject !== '' && preg_match(self::AUTO_REPLY_SUBJECT, $subject)) {
            return 'auto-reply-subject';
        }
        if (preg_match(self::INVISIBLE_CHARS, $subject . $name)) {
            return 'invisible-characters';
        }
        if (preg_match(self::SYSTEM_LOCAL_PART, $local)
                || preg_match(self::ROLE_LOCAL_PART, $local)
                || preg_match(self::NOREPLY_TOKEN, $local)) {
            return 'automated-mailbox';
        }
        $labels = explode('.', $domain);
        if (in_array('bounces', $labels, true)
                || (count($labels) >= 3 && preg_match(self::AUTOMATED_SUBDOMAIN, $labels[0]))) {
            return 'automated-subdomain';
        }
        // zgfmg@zgfmg.cqxbu.com: throwaway spam hosts mirror the mailbox name
        // as a subdomain. coval@coval.com.sv is a real company and stays.
        if (count($labels) >= 3 && $labels[0] === $local && $domain !== self::orgDomain($domain)) {
            return 'mirrored-subdomain';
        }
        if (!empty($context['own_domains']) && self::domainInList($domain, $context['own_domains'])) {
            return 'own-domain';
        }
        if (self::domainInList($domain, self::BRAND_DOMAINS)) {
            return 'brand-domain';
        }
        if (!empty($context['skip_list'])) {
            $skip = array_map('strtolower', $context['skip_list']);
            if (in_array($email, $skip, true)) {
                return 'blocked-address';
            }
            if (self::domainInList($domain, array_filter($skip, function ($d) { return strpos($d, '@') === false; }))) {
                return 'blocked-domain';
            }
        }

        $parsed = is_array($headers) ? self::normalizeHeaders($headers) : self::parseHeaders((string) $headers);
        if ($parsed) {
            $sender = isset($context['invite_sender']) ? (string) $context['invite_sender'] : '';
            return self::headerReason($parsed, $email, $sender);
        }
        return null;
    }

    /**
     * Reason derived from the inbound message headers, or null.
     *
     * @param array<string,string[]> $headers      lowercase names → values, in header order
     * @param string                 $email        the sender address
     * @param string                 $inviteSender address our invitation is sent from
     */
    public static function headerReason(array $headers, $email = '', $inviteSender = '') {
        // Replying to a Message-ID we generated for the unthreaded invitation
        // means this "new ticket" is an answer to it — typically a help desk
        // acknowledgement that changed the subject.
        $inviteSender = strtolower(trim($inviteSender));
        if ($inviteSender !== '') {
            foreach (array('in-reply-to', 'references') as $h) {
                if (isset($headers[$h])
                        && strpos(strtolower(implode(' ', $headers[$h])), '-' . $inviteSender . '>') !== false) {
                    return 'reply-to-invite';
                }
            }
        }

        $personal = self::isPersonalMailboxProvider($headers);
        foreach (self::AUTOMATION_HEADERS as $name => $matcher) {
            if (!isset($headers[$name])) { continue; }
            if ($personal && in_array($name, self::PERSONAL_PROVIDER_EXEMPT, true)) { continue; }
            foreach ($headers[$name] as $value) {
                if ($matcher === '*') {
                    return 'header:' . $name;
                }
                $upper = strtoupper($value);
                foreach ($matcher as $needle) {
                    if (strpos($upper, $needle) !== false) {
                        return 'header:' . $name;
                    }
                }
            }
        }

        // RFC 3834: any Auto-Submitted value other than "no" is machine-sent.
        if (isset($headers['auto-submitted'])) {
            foreach ($headers['auto-submitted'] as $value) {
                if (strtolower(trim($value)) !== 'no') {
                    return 'header:auto-submitted';
                }
            }
        }
        // Null reverse-path = delivery status notification.
        if (isset($headers['return-path'])) {
            foreach ($headers['return-path'] as $value) {
                if (trim($value) === '<>') {
                    return 'bounce';
                }
            }
        }
        if (isset($headers['content-type'])) {
            foreach ($headers['content-type'] as $value) {
                if (stripos($value, 'report-type=delivery-status') !== false
                        || stripos($value, 'multipart/report') !== false) {
                    return 'bounce';
                }
            }
        }
        // Spam verdict: only the one our own MTA appended (the last copy);
        // earlier copies could have been written by the sender.
        $flag = self::lastValue($headers, 'x-spam-flag');
        $status = self::lastValue($headers, 'x-spam-status');
        if (($flag !== null && strtoupper(trim($flag)) === 'YES')
                || ($status !== null && stripos(ltrim($status), 'yes') === 0)) {
            return 'spam';
        }
        // Spam blasts are commonly addressed to the sender itself with the
        // real recipients in Bcc. A customer writing to support never does this.
        if ($email !== '' && isset($headers['to'])) {
            $to = self::addressesIn(implode(',', $headers['to']));
            if ($to && array_values(array_unique($to)) === array($email)) {
                return 'self-addressed';
            }
        }
        return self::authReason($headers, $email);
    }

    /**
     * 'unauthenticated-sender' when the receiving MTA's SpamAssassin report
     * shows the From address was neither DKIM-signed by its domain nor sent
     * from an SPF-authorized server of it — i.e. likely forged, and mailing
     * it would be backscatter to an innocent third party. Fails open (null)
     * whenever the report is missing or the checks were inconclusive.
     */
    public static function authReason(array $headers, $email) {
        $rules = self::spamAssassinRules($headers);
        if ($rules === null) {
            return null;
        }
        $has = function ($rule) use ($rules) { return isset($rules[$rule]); };

        $spfEvaluated = $has('SPF_PASS') || $has('SPF_FAIL') || $has('SPF_SOFTFAIL') || $has('SPF_NEUTRAL')
            || $has('SPF_NONE') || $has('SPF_PERMERROR') || $has('T_SPF_PERMERROR');
        if (!$spfEvaluated || $has('DKIM_VALID_AU')) {
            return null;
        }
        // Small-business SPF misconfigured (~all) while the provider DKIM-signs: not a spoof.
        if (($has('SPF_SOFTFAIL') || $has('SPF_NEUTRAL')) && $has('DKIM_VALID')) {
            return null;
        }
        // Fail open when the evidence is incomplete: unknown envelope sender,
        // or a DKIM signature that could be verified neither way (DNS trouble).
        $returnPath = self::addressesIn((string) self::firstValue($headers, 'return-path'));
        $at = strrpos($email, '@');
        if (!$returnPath || $at === false) {
            return null;
        }
        if ($has('DKIM_SIGNED') && !$has('DKIM_VALID') && !$has('DKIM_INVALID') && !$has('T_DKIM_INVALID')) {
            return null;
        }
        $rpAt = strrpos($returnPath[0], '@');
        if ($has('SPF_PASS')
                && self::orgDomain(substr($returnPath[0], $rpAt + 1)) === self::orgDomain(substr($email, $at + 1))) {
            return null;
        }
        return 'unauthenticated-sender';
    }

    /**
     * Rule names from the last X-Spam-Report / X-Ham-Report header, parsed
     * only after "Content analysis details:" so text quoted in the content
     * preview can't inject rule names. Null when no report is present.
     *
     * @return array<string,bool>|null
     */
    public static function spamAssassinRules(array $headers) {
        $report = null;
        foreach (array('x-ham-report', 'x-spam-report') as $h) {
            $v = self::lastValue($headers, $h);
            if ($v !== null) { $report = $v; }
        }
        if ($report === null) {
            return null;
        }
        $pos = strripos($report, 'Content analysis details:');
        if ($pos === false) {
            return null;
        }
        preg_match_all('/(?:^|\s)-?\d+(?:\.\d+)?\s+([A-Z][A-Z0-9_]{2,})(?=\s|$)/', substr($report, $pos), $m);
        return array_fill_keys($m[1], true);
    }

    /**
     * Parse a raw RFC 822 header block into lowercase names → list of values.
     * Folded continuation lines are joined; duplicate headers are kept in order.
     *
     * @return array<string,string[]>
     */
    public static function parseHeaders($raw) {
        $out = array();
        $raw = (string) $raw;
        if (trim($raw) === '') { return $out; }
        $last = null;
        foreach (preg_split('/\r\n|\r|\n/', $raw) as $line) {
            if ($line === '') { continue; }
            if (($line[0] === ' ' || $line[0] === "\t") && $last !== null) {
                $i = count($out[$last]) - 1;
                $out[$last][$i] .= ' ' . trim($line);
                continue;
            }
            $colon = strpos($line, ':');
            if ($colon === false || $colon === 0) { $last = null; continue; }
            $name = strtolower(trim(substr($line, 0, $colon)));
            $out[$name][] = trim(substr($line, $colon + 1));
            $last = $name;
        }
        return $out;
    }

    /**
     * Split an admin-entered list (newlines, commas or spaces) of domains
     * and/or full addresses into normalized entries. Invalid ones are dropped.
     *
     * @return string[]
     */
    public static function parseSkipList($text) {
        $entries = array();
        foreach (preg_split('/[\s,;]+/', strtolower((string) $text)) as $e) {
            $e = trim($e, " .\t");
            $e = ltrim($e, '@');
            if ($e === '') { continue; }
            if (preg_match('/^[a-z0-9-]+(\.[a-z0-9-]+)+$/', $e)
                    || preg_match('/^[^\s@]+@[a-z0-9-]+(\.[a-z0-9-]+)+$/', $e)) {
                $entries[] = $e;
            }
        }
        return array_values(array_unique($entries));
    }

    /**
     * Registrable ("organizational") domain, good enough for comparing two
     * addresses: mail.empresa.com.mx → empresa.com.mx, a.b.example.com → example.com.
     */
    public static function orgDomain($domain) {
        $labels = explode('.', strtolower($domain));
        $n = count($labels);
        if ($n >= 3 && strlen($labels[$n - 1]) === 2
                && in_array($labels[$n - 2], array('com', 'net', 'org', 'gob', 'gov', 'edu', 'co', 'ac', 'mil', 'ne', 'or'), true)) {
            return implode('.', array_slice($labels, -3));
        }
        return implode('.', array_slice($labels, -2));
    }

    private static function isPersonalMailboxProvider(array $headers) {
        if (isset($headers['x-wm-sent-timestamp'])) {
            return true;
        }
        foreach (array('x-mailer', 'x-original-mailer') as $h) {
            $v = self::firstValue($headers, $h);
            if ($v !== null && stripos(ltrim($v), 'Amazon WorkMail') === 0) {
                return true;
            }
        }
        $feedback = self::firstValue($headers, 'feedback-id');
        if ($feedback !== null && preg_match('/:(Ext:ProtonMail|user:proton)\s*$/i', $feedback)) {
            return true;
        }
        $image = self::firstValue($headers, 'x-image-url');
        return $image !== null && stripos($image, 'micorreo.telmex.com') !== false;
    }

    private static function normalizeHeaders(array $headers) {
        $out = array();
        foreach ($headers as $name => $value) {
            $key = strtolower(trim((string) $name));
            foreach ((array) $value as $v) {
                $out[$key][] = trim((string) $v);
            }
        }
        return $out;
    }

    private static function firstValue(array $headers, $name) {
        return isset($headers[$name][0]) ? $headers[$name][0] : null;
    }

    private static function lastValue(array $headers, $name) {
        return isset($headers[$name]) && $headers[$name] ? end($headers[$name]) : null;
    }

    private static function domainInList($domain, $list) {
        foreach ($list as $d) {
            $d = strtolower(trim((string) $d));
            if ($d === '') { continue; }
            if ($domain === $d || substr($domain, -strlen($d) - 1) === '.' . $d) {
                return true;
            }
        }
        return false;
    }

    private static function addressesIn($value) {
        preg_match_all('/[^\s<>",;:()]+@[^\s<>",;:()]+/', strtolower($value), $m);
        return $m[0];
    }
}
